// DEFINE ALL OF THE APP'S ACTIONS HERE
// DEFINE STATES PER CATEGORY

const cardSetStates = [
  'FETCH_SETS_START',
  'FETCH_SETS_FINISH',
  'FETCH_SETS_FAIL',

  'TOGGLE_SET_FAVORITE',

  'SETS_NEW_RECEIVED',

]

// SET transitions
export const FETCH_SETS_START = 'FETCH_SETS_START';
export const FETCH_SETS_FINISH = 'FETCH_SETS_FINISH';

export const FETCH_SETS_RECEIVED = 'FETCH_SETS_RECEIVED';
export const FETCH_SETS_FAIL = 'FETCH_SETS_FAIL';

export const TOGGLE_SET_FAVORITE ='TOGGLE_SET_FAVORITE';

export const GENERIC_WAIT_START = 'GENERIC_WAIT_START';
export const GENERIC_WAIT_FINISH = 'GENERIC_WAIT_FINISH';


// export const SET_SEARCH = 'SET_SEARCH'
// export const DISPLAY_SET = 'DISPLAY_SET'



// ACTIONS DEFINE STATE TRANSITIONS
// FOR FINITE STATE MACHINES